language: go

go:
  - 1.10.x

sudo: required

before_install:
  - sudo apt-get install -y ca-certificates

install:
  - go get github.com/golang/dep/cmd/dep && dep ensure

script:
  - go test -v --race --timeout 30s
